name: Deploy to Portainer

on:
  push:
    branches:
      - main  # ou master, verifique sua branch principal

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar Webhook do Portainer
        ## O comando curl apenas acessa o link, avisando o Portainer para atualizar
        run: curl -X POST "${{ secrets.PORTAINER_WEBHOOK }}"